### ISSUE TITLE
vok-helloworld-app: Crashes when cut and pasting MyWelcomeView.kt

### ISSUE THREAD

**Issue by a-cosmic-jaw** [mvysny/vaadin-on-kotlin#101]
`jakarta.servlet.ServletException: java.lang.reflect.InvocationTargetException
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:103)
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.onStartup(ClassLoaderAwareServletContainerInitializer.java:122)
	at org.eclipse.jetty.ee10.servlet.ServletContainerInitializerHolder.doStart(ServletContainerInitializerHolder.java:153)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletContainerInitializerStarter.doStart(ServletContextHandler.java:3041)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.startContext(ServletContextHandler.java:1280)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.startContext(WebAppContext.java:1210)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0(ServletContextHandler.java:1042)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1203)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart(ServletContextHandler.java:1039)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart(WebAppContext.java:484)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:601)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:395)
	at org.eclipse.jetty.server.Server.doStart(Server.java:542)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at com.github.mvysny.vaadinboot.VaadinBoot.start(VaadinBoot.java:293)
	at com.github.mvysny.vaadinboot.VaadinBoot.run(VaadinBoot.java:235)
	at com.example.vok.MainKt.main(Main.kt:9)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:98)
	... 23 more
Caused by: jakarta.servlet.ServletException: java.lang.reflect.InvocationTargetException
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:103)
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$4(ClassLoaderAwareServletContainerInitializer.java:117)
	at com.vaadin.flow.server.startup.DeferredServletContextInitializers.runInitializers(DeferredServletContextInitializers.java:86)
	at com.vaadin.flow.server.startup.LookupServletContainerInitializer.lambda$process$0(LookupServletContainerInitializer.java:116)
	at com.vaadin.flow.di.LookupInitializer.initialize(LookupInitializer.java:283)
	at com.vaadin.flow.server.startup.LookupServletContainerInitializer.process(LookupServletContainerInitializer.java:104)
	... 28 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:98)
	... 33 more
Caused by: jakarta.servlet.ServletException: com.vaadin.flow.server.startup.VaadinInitializerException: Exception while registering Routes on servlet startup
	at com.vaadin.flow.server.startup.VaadinServletContextStartupInitializer.process(VaadinServletContextStartupInitializer.java:44)
	... 38 more
Caused by: com.vaadin.flow.server.startup.VaadinInitializerException: Exception while registering Routes on servlet startup
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.initialize(RouteRegistryInitializer.java:77)
	at com.vaadin.flow.server.startup.VaadinServletContextStartupInitializer.process(VaadinServletContextStartupInitializer.java:42)
	... 38 more
Caused by: com.vaadin.flow.server.AmbiguousRouteConfigurationException: Navigation targets must have unique routes, found navigation targets 'com.example.vok.WelcomeView' and 'com.example.vok.MyWelcomeView' with the same route.
	at com.vaadin.flow.router.internal.RouteSegment.ambigousException(RouteSegment.java:806)
	at com.vaadin.flow.router.internal.RouteSegment.ambigousTarget(RouteSegment.java:801)
	at com.vaadin.flow.router.internal.RouteSegment.setRouteTarget(RouteSegment.java:487)
	at com.vaadin.flow.router.internal.RouteSegment.addSubRoute(RouteSegment.java:458)
	at com.vaadin.flow.router.internal.RouteSegment.addSubRoute(RouteSegment.java:267)
	at com.vaadin.flow.router.internal.RouteModel.addRoute(RouteModel.java:130)
	at com.vaadin.flow.router.internal.ConfigureRoutes.setRoute(ConfigureRoutes.java:175)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.lambda$setRoute$2df6994$1(AbstractRouteRegistry.java:302)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.lambda$configureWithFullTemplate$ccc9e4ad$1(AbstractRouteRegistry.java:353)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.configure(AbstractRouteRegistry.java:99)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.configureWithFullTemplate(AbstractRouteRegistry.java:352)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.setRoute(AbstractRouteRegistry.java:300)
	at com.vaadin.flow.server.startup.ApplicationRouteRegistry.setRoute(ApplicationRouteRegistry.java:128)
	at com.vaadin.flow.router.RouteConfiguration.setAnnotatedRoute(RouteConfiguration.java:221)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.setAnnotatedRoutes(RouteRegistryInitializer.java:126)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.lambda$configureRoutes$5af67ca1$1(RouteRegistryInitializer.java:119)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.update(AbstractRouteRegistry.java:110)
	at com.vaadin.flow.router.RouteConfiguration.update(RouteConfiguration.java:199)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.configureRoutes(RouteRegistryInitializer.java:119)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.lambda$initialize$b993c304$1(RouteRegistryInitializer.java:72)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.update(AbstractRouteRegistry.java:110)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.initialize(RouteRegistryInitializer.java:67)
	... 39 more
2024-04-18 11:19:21.753 [main] INFO com.github.mvysny.vaadinboot.VaadinBoot - Failed to start
2024-04-18 11:19:21.758 [main] INFO com.github.mvysny.vaadinboot.VaadinBoot - Stopped
Exception in thread "main" jakarta.servlet.ServletException: java.lang.reflect.InvocationTargetException
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:103)
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.onStartup(ClassLoaderAwareServletContainerInitializer.java:122)
	at org.eclipse.jetty.ee10.servlet.ServletContainerInitializerHolder.doStart(ServletContainerInitializerHolder.java:153)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletContainerInitializerStarter.doStart(ServletContextHandler.java:3041)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.startContext(ServletContextHandler.java:1280)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.startContext(WebAppContext.java:1210)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0(ServletContextHandler.java:1042)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1203)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart(ServletContextHandler.java:1039)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart(WebAppContext.java:484)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:601)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:395)
	at org.eclipse.jetty.server.Server.doStart(Server.java:542)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at com.github.mvysny.vaadinboot.VaadinBoot.start(VaadinBoot.java:293)
	at com.github.mvysny.vaadinboot.VaadinBoot.run(VaadinBoot.java:235)
	at com.example.vok.MainKt.main(Main.kt:9)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:98)
	... 23 more
Caused by: jakarta.servlet.ServletException: java.lang.reflect.InvocationTargetException
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:103)
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$4(ClassLoaderAwareServletContainerInitializer.java:117)
	at com.vaadin.flow.server.startup.DeferredServletContextInitializers.runInitializers(DeferredServletContextInitializers.java:86)
	at com.vaadin.flow.server.startup.LookupServletContainerInitializer.lambda$process$0(LookupServletContainerInitializer.java:116)
	at com.vaadin.flow.di.LookupInitializer.initialize(LookupInitializer.java:283)
	at com.vaadin.flow.server.startup.LookupServletContainerInitializer.process(LookupServletContainerInitializer.java:104)
	... 28 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.lambda$onStartup$2(ClassLoaderAwareServletContainerInitializer.java:98)
	... 33 more
Caused by: jakarta.servlet.ServletException: com.vaadin.flow.server.startup.VaadinInitializerException: Exception while registering Routes on servlet startup
	at com.vaadin.flow.server.startup.VaadinServletContextStartupInitializer.process(VaadinServletContextStartupInitializer.java:44)
	... 38 more
Caused by: com.vaadin.flow.server.startup.VaadinInitializerException: Exception while registering Routes on servlet startup
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.initialize(RouteRegistryInitializer.java:77)
	at com.vaadin.flow.server.startup.VaadinServletContextStartupInitializer.process(VaadinServletContextStartupInitializer.java:42)
	... 38 more
Caused by: com.vaadin.flow.server.AmbiguousRouteConfigurationException: Navigation targets must have unique routes, found navigation targets 'com.example.vok.WelcomeView' and 'com.example.vok.MyWelcomeView' with the same route.
	at com.vaadin.flow.router.internal.RouteSegment.ambigousException(RouteSegment.java:806)
	at com.vaadin.flow.router.internal.RouteSegment.ambigousTarget(RouteSegment.java:801)
	at com.vaadin.flow.router.internal.RouteSegment.setRouteTarget(RouteSegment.java:487)
	at com.vaadin.flow.router.internal.RouteSegment.addSubRoute(RouteSegment.java:458)
	at com.vaadin.flow.router.internal.RouteSegment.addSubRoute(RouteSegment.java:267)
	at com.vaadin.flow.router.internal.RouteModel.addRoute(RouteModel.java:130)
	at com.vaadin.flow.router.internal.ConfigureRoutes.setRoute(ConfigureRoutes.java:175)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.lambda$setRoute$2df6994$1(AbstractRouteRegistry.java:302)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.lambda$configureWithFullTemplate$ccc9e4ad$1(AbstractRouteRegistry.java:353)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.configure(AbstractRouteRegistry.java:99)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.configureWithFullTemplate(AbstractRouteRegistry.java:352)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.setRoute(AbstractRouteRegistry.java:300)
	at com.vaadin.flow.server.startup.ApplicationRouteRegistry.setRoute(ApplicationRouteRegistry.java:128)
	at com.vaadin.flow.router.RouteConfiguration.setAnnotatedRoute(RouteConfiguration.java:221)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.setAnnotatedRoutes(RouteRegistryInitializer.java:126)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.lambda$configureRoutes$5af67ca1$1(RouteRegistryInitializer.java:119)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.update(AbstractRouteRegistry.java:110)
	at com.vaadin.flow.router.RouteConfiguration.update(RouteConfiguration.java:199)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.configureRoutes(RouteRegistryInitializer.java:119)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.lambda$initialize$b993c304$1(RouteRegistryInitializer.java:72)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.update(AbstractRouteRegistry.java:110)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.initialize(RouteRegistryInitializer.java:67)
	... 39 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Users/VIP/Library/Java/JavaVirtualMachines/corretto-17.0.9/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s`

**Comment by mvysny** [comment]
Hi, yes, the reason is that both WelcomeView and MyWelcomeView are mapped to the same path.
